---
deployment:
  tasks:
    - export HOME=/homeX/madebran
    - export COMPOSER_HOME=/homeX/madebran/.composer
    - export COMPOSER_BIN=/homeX/madebran/bin
    - export DEPLOYPATH=/homeX/madebran/public_html/

    - /bin/mkdir -p $COMPOSER_BIN
    - /bin/mkdir -p $COMPOSER_HOME
    - /bin/mkdir -p $DEPLOYPATH

    - |
      if [ ! -f "$COMPOSER_BIN/composer.phar" ]; then
        php -r "copy('https://getcomposer.org/installer', '/homeX/madebran/composer-setup.php');"
        php /homeX/madebran/composer-setup.php --install-dir=$COMPOSER_BIN --filename=composer.phar
        /bin/rm -f /homeX/madebran/composer-setup.php
      fi

    - |
      find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec /bin/cp -R {} "$DEPLOYPATH" \;

    - cd $DEPLOYPATH

    - php $COMPOSER_BIN/composer.phar install --no-dev --optimize-autoloader --no-interaction

    - php mkdir.php

    - php protected/yiic migrate up --interactive=0